// Mock data for the entire system

// Available system permissions
export const systemPermissions = [
  { id: "review_teachers", name: "Review Teachers", description: "Can approve or reject teacher registrations" },
  { id: "review_bookings", name: "Review Bookings", description: "Can verify and manage student bookings" },
  { id: "manage_users", name: "Manage Users", description: "Can edit user profiles and status" },
  { id: "view_activity_logs", name: "View Activity Logs", description: "Can access system activity logs" },
  { id: "manage_services", name: "Manage Services", description: "Can edit or remove tutoring services" },
  { id: "send_announcements", name: "Send Announcements", description: "Can send platform-wide announcements" },
]

export const mockUsers: Record<string, any> = {
  admin: {
    id: "admin-1",
    email: "admin@teachconnect.com",
    password: "admin123",
    firstName: "Admin",
    lastName: "User",
    middleName: "",
    role: "admin",
    status: "approved",
    permissions: ["review_teachers", "review_bookings", "manage_users", "view_activity_logs", "manage_services", "send_announcements"],
    createdAt: new Date("2024-01-01"),
  },
  teacher1: {
    id: "teacher-1",
    email: "john@example.com",
    password: "teacher123",
    firstName: "John",
    lastName: "Smith",
    middleName: "Michael",
    role: "teacher",
    status: "approved",
    phone: "+63 917 123 4567",
    address: "123 Main St, Quezon City, Metro Manila",
    bio: "Experienced mathematics and physics teacher with over 8 years of teaching experience. Passionate about making complex concepts easy to understand.",
    subjects: ["Mathematics", "Physics", "Statistics"],
    experience: "8 years",
    education: "Master of Science in Mathematics, University of the Philippines",
    certifications: ["Licensed Professional Teacher", "TESDA NC II - Mathematics"],
    uploadedIds: {
      governmentId: "/uploads/teacher-1/government-id.jpg",
      teachingCertificate: "/uploads/teacher-1/teaching-certificate.pdf",
    },
    createdAt: new Date("2024-01-15"),
    approvedAt: new Date("2024-01-16"),
  },
  teacher2: {
    id: "teacher-2",
    email: "sarah@example.com",
    password: "teacher123",
    firstName: "Sarah",
    lastName: "Johnson",
    middleName: "Marie",
    role: "teacher",
    status: "pending",
    phone: "+63 918 987 6543",
    address: "456 Oak Ave, Makati City, Metro Manila",
    bio: "English literature and writing coach specializing in college preparation and essay writing. I help students express themselves clearly and confidently.",
    subjects: ["English Literature", "Creative Writing", "Essay Writing"],
    experience: "5 years",
    education: "Bachelor of Arts in English Literature, Ateneo de Manila University",
    certifications: ["Licensed Professional Teacher", "IELTS Certified Trainer"],
    uploadedIds: {
      governmentId: "/uploads/teacher-2/passport.jpg",
      teachingCertificate: "/uploads/teacher-2/prc-license.pdf",
    },
    createdAt: new Date("2024-02-01"),
  },
  teacher3: {
    id: "teacher-3",
    email: "miguel@example.com",
    password: "teacher123",
    firstName: "Miguel",
    lastName: "Santos",
    middleName: "Reyes",
    role: "teacher",
    status: "pending",
    phone: "+63 919 456 7890",
    address: "789 Rizal Blvd, Pasig City, Metro Manila",
    bio: "Science teacher with expertise in Chemistry and Biology. I believe in hands-on learning and practical applications of scientific concepts.",
    subjects: ["Chemistry", "Biology", "General Science"],
    experience: "6 years",
    education: "Bachelor of Science in Chemistry, De La Salle University",
    certifications: ["Licensed Professional Teacher", "Laboratory Safety Certified"],
    uploadedIds: {
      governmentId: "/uploads/teacher-3/drivers-license.jpg",
      teachingCertificate: "/uploads/teacher-3/teaching-cert.pdf",
      additionalCert: "/uploads/teacher-3/lab-safety-cert.pdf",
    },
    createdAt: new Date("2024-02-10"),
  },
  teacher4: {
    id: "teacher-4",
    email: "anna@example.com",
    password: "teacher123",
    firstName: "Anna",
    lastName: "Cruz",
    middleName: "Liza",
    role: "teacher",
    status: "pending",
    phone: "+63 920 321 0987",
    address: "321 Bonifacio St, Taguig City, Metro Manila",
    bio: "Filipino and Social Studies teacher dedicated to helping students understand our culture and history. I make learning engaging through storytelling.",
    subjects: ["Filipino", "Social Studies", "Philippine History"],
    experience: "4 years",
    education: "Bachelor of Secondary Education, Philippine Normal University",
    certifications: ["Licensed Professional Teacher"],
    uploadedIds: {
      governmentId: "/uploads/teacher-4/national-id.jpg",
      teachingCertificate: "/uploads/teacher-4/prc-license.pdf",
    },
    createdAt: new Date("2024-02-12"),
  },
  student1: {
    id: "student-1",
    email: "student1@example.com",
    password: "student123",
    firstName: "Maria",
    lastName: "Garcia",
    middleName: "Elena",
    role: "student",
    status: "approved",
    createdAt: new Date("2024-01-20"),
  },
  student2: {
    id: "student-2",
    email: "student2@example.com",
    password: "student123",
    firstName: "David",
    lastName: "Chen",
    middleName: "Lee",
    role: "student",
    status: "approved",
    createdAt: new Date("2024-02-05"),
  },
}

// Teachers offering their tutoring services (students apply to be tutored)
export const mockJobs: Record<string, any> = {
  "job-1": {
    id: "job-1",
    teacherId: "teacher-1",
    teacherName: "John Smith",
    title: "Mathematics Tutoring - Grade 10-12",
    description: "I offer comprehensive mathematics tutoring for high school students. Specializing in Algebra, Calculus, and Statistics. 5+ years of teaching experience.",
    salary: "500-800 PHP/hour",
    location: "Manila, Metro Manila",
    status: "active",
    applicants: 5,
    createdAt: new Date("2024-02-10"),
  },
  "job-2": {
    id: "job-2",
    teacherId: "teacher-1",
    teacherName: "John Smith",
    title: "Physics Tutoring - Online Sessions",
    description: "Online physics tutoring for high school students. Flexible schedule, personalized lesson plans. I make physics concepts easy to understand.",
    salary: "400-600 PHP/hour",
    location: "Remote",
    status: "active",
    applicants: 3,
    createdAt: new Date("2024-02-08"),
  },
  "job-3": {
    id: "job-3",
    teacherId: "teacher-2",
    teacherName: "Sarah Johnson",
    title: "English Literature & Writing Coach",
    description: "I provide English literature and writing coaching for Grade 11-12 students. Help with essay writing, literary analysis, and college prep.",
    salary: "550-750 PHP/hour",
    location: "Quezon City, Metro Manila",
    status: "closed",
    applicants: 8,
    createdAt: new Date("2024-01-25"),
  },
}

// Student applications to be tutored by a teacher
export const mockApplications: Record<string, any> = {
  "app-1": {
    id: "app-1",
    jobId: "job-1",
    studentId: "student-1",
    studentName: "Maria Garcia",
    jobTitle: "Mathematics Tutoring - Grade 10-12",
    coverLetter:
      "I am very interested in your math tutoring. I need help preparing for my college entrance exams.",
    status: "pending",
    createdAt: new Date("2024-02-11"),
  },
  "app-2": {
    id: "app-2",
    jobId: "job-1",
    studentId: "student-2",
    studentName: "David Chen",
    jobTitle: "Mathematics Tutoring - Grade 10-12",
    coverLetter: "I'm struggling with calculus and would love your guidance.",
    status: "accepted",
    createdAt: new Date("2024-02-12"),
  },
  "app-3": {
    id: "app-3",
    jobId: "job-2",
    studentId: "student-1",
    studentName: "Maria Garcia",
    jobTitle: "Physics Tutoring - Online Sessions",
    coverLetter: "Physics is challenging for me. I'm ready to learn and improve.",
    status: "pending",
    createdAt: new Date("2024-02-11"),
  },
}

export const mockLogs: any[] = [
  {
    id: "log-1",
    userId: "teacher-1",
    userName: "John Smith",
    action: "service_posted",
    description: "Posted new tutoring service: Mathematics Tutoring - Grade 10-12",
    timestamp: new Date("2024-02-10T10:30:00"),
  },
  {
    id: "log-2",
    userId: "student-1",
    userName: "Maria Garcia",
    action: "application_submitted",
    description: "Applied for tutoring: Mathematics Tutoring - Grade 10-12",
    timestamp: new Date("2024-02-11T14:45:00"),
  },
  {
    id: "log-3",
    userId: "admin-1",
    userName: "Admin User",
    action: "teacher_approved",
    description: "Approved teacher: John Smith",
    timestamp: new Date("2024-01-15T09:15:00"),
  },
  {
    id: "log-4",
    userId: "teacher-2",
    userName: "Sarah Johnson",
    action: "registration_pending",
    description: "New teacher registration pending verification",
    timestamp: new Date("2024-02-01T11:20:00"),
  },
  {
    id: "log-5",
    userId: "student-2",
    userName: "David Chen",
    action: "registered",
    description: "New student registration completed",
    timestamp: new Date("2024-02-05T16:30:00"),
  },
]

// Students requesting tutors (teachers can offer to help)
export const mockTutorRequests: Record<string, any> = {
  "request-1": {
    id: "request-1",
    studentId: "student-1",
    studentName: "Maria Garcia",
    subject: "Calculus",
    gradeLevel: "College",
    description: "Need help understanding differential equations and integration techniques for my university calculus course.",
    budget: "300-500 PHP/hour",
    schedule: "Weekends, 2-4 PM",
    location: "Online or Manila Area",
    status: "active",
    createdAt: new Date("2024-02-14"),
  },
  "request-2": {
    id: "request-2",
    studentId: "student-2",
    studentName: "David Chen",
    subject: "English Writing",
    gradeLevel: "Grade 11",
    description: "Looking for a tutor to help improve my essay writing skills for college applications.",
    budget: "250-400 PHP/hour",
    schedule: "Weekday evenings, after 5 PM",
    location: "Quezon City or Online",
    status: "active",
    createdAt: new Date("2024-02-12"),
  },
  "request-3": {
    id: "request-3",
    studentId: "student-1",
    studentName: "Maria Garcia",
    subject: "Chemistry",
    gradeLevel: "Grade 12",
    description: "Preparing for university entrance exams, need help with organic chemistry.",
    budget: "400-600 PHP/hour",
    schedule: "Flexible",
    location: "Online",
    status: "active",
    createdAt: new Date("2024-02-10"),
  },
}
