// Mock data for the entire system

// Available system permissions
export const systemPermissions = [
  { id: "review_teachers", name: "Review Teachers", description: "Can approve or reject teacher registrations" },
  { id: "manage_jobs", name: "Manage Jobs", description: "Can create and manage job postings" },
  { id: "manage_users", name: "Manage Users", description: "Can edit user profiles and status" },
  { id: "view_activity_logs", name: "View Activity Logs", description: "Can access system activity logs" },
  { id: "view_applications", name: "View Applications", description: "Can view teacher job applications" },
  { id: "send_announcements", name: "Send Announcements", description: "Can send platform-wide announcements" },
]

export const mockUsers: Record<string, any> = {
  admin: {
    id: "admin-1",
    email: "admin@teachconnect.com",
    password: "admin123",
    firstName: "Admin",
    lastName: "User",
    middleName: "",
    role: "admin",
    status: "approved",
    permissions: ["review_teachers", "manage_jobs", "manage_users", "view_activity_logs", "view_applications", "send_announcements"],
    createdAt: new Date("2026-01-01"),
  },
  teacher1: {
    id: "teacher-1",
    email: "john@example.com",
    password: "teacher123",
    firstName: "John",
    lastName: "Smith",
    middleName: "Michael",
    role: "teacher",
    status: "approved",
    phone: "+63 917 123 4567",
    address: "123 Main St, Quezon City, Metro Manila",
    bio: "Experienced mathematics and physics teacher with over 8 years of teaching experience. Passionate about making complex concepts easy to understand.",
    subjects: ["Mathematics", "Physics", "Statistics"],
    experience: "8 years",
    education: "Master of Science in Mathematics, University of the Philippines",
    certifications: ["Licensed Professional Teacher", "TESDA NC II - Mathematics"],
    uploadedIds: {
      governmentId: "/uploads/teacher-1/government-id.jpg",
      teachingCertificate: "/uploads/teacher-1/teaching-certificate.pdf",
    },
    createdAt: new Date("2026-01-15"),
    approvedAt: new Date("2026-01-16"),
  },
  teacher2: {
    id: "teacher-2",
    email: "sarah@example.com",
    password: "teacher123",
    firstName: "Sarah",
    lastName: "Johnson",
    middleName: "Marie",
    role: "teacher",
    status: "pending",
    phone: "+63 918 987 6543",
    address: "456 Oak Ave, Makati City, Metro Manila",
    bio: "English literature and writing coach specializing in college preparation and essay writing. I help students express themselves clearly and confidently.",
    subjects: ["English Literature", "Creative Writing", "Essay Writing"],
    experience: "5 years",
    education: "Bachelor of Arts in English Literature, Ateneo de Manila University",
    certifications: ["Licensed Professional Teacher", "IELTS Certified Trainer"],
    uploadedIds: {
      governmentId: "/uploads/teacher-2/passport.jpg",
      teachingCertificate: "/uploads/teacher-2/prc-license.pdf",
    },
    createdAt: new Date("2026-02-01"),
  },
  teacher3: {
    id: "teacher-3",
    email: "miguel@example.com",
    password: "teacher123",
    firstName: "Miguel",
    lastName: "Santos",
    middleName: "Reyes",
    role: "teacher",
    status: "pending",
    phone: "+63 919 456 7890",
    address: "789 Rizal Blvd, Pasig City, Metro Manila",
    bio: "Science teacher with expertise in Chemistry and Biology. I believe in hands-on learning and practical applications of scientific concepts.",
    subjects: ["Chemistry", "Biology", "General Science"],
    experience: "6 years",
    education: "Bachelor of Science in Chemistry, De La Salle University",
    certifications: ["Licensed Professional Teacher", "Laboratory Safety Certified"],
    uploadedIds: {
      governmentId: "/uploads/teacher-3/drivers-license.jpg",
      teachingCertificate: "/uploads/teacher-3/teaching-cert.pdf",
      additionalCert: "/uploads/teacher-3/lab-safety-cert.pdf",
    },
    createdAt: new Date("2026-02-10"),
  },
  teacher4: {
    id: "teacher-4",
    email: "anna@example.com",
    password: "teacher123",
    firstName: "Anna",
    lastName: "Cruz",
    middleName: "Liza",
    role: "teacher",
    status: "pending",
    phone: "+63 920 321 0987",
    address: "321 Bonifacio St, Taguig City, Metro Manila",
    bio: "Filipino and Social Studies teacher dedicated to helping students understand our culture and history. I make learning engaging through storytelling.",
    subjects: ["Filipino", "Social Studies", "Philippine History"],
    experience: "4 years",
    education: "Bachelor of Secondary Education, Philippine Normal University",
    certifications: ["Licensed Professional Teacher"],
    uploadedIds: {
      governmentId: "/uploads/teacher-4/national-id.jpg",
      teachingCertificate: "/uploads/teacher-4/prc-license.pdf",
    },
    createdAt: new Date("2026-02-12"),
  },
}

// Job postings created by admin
export const mockJobs: Record<string, any> = {
  "job-1": {
    id: "job-1",
    adminId: "admin-1",
    title: "High School Mathematics Teacher",
    subject: "Mathematics",
    description: "We are looking for an experienced mathematics teacher for grades 10-12. The ideal candidate should be proficient in Algebra, Calculus, and Statistics with at least 3 years of teaching experience.",
    requirements: "Bachelor's degree in Mathematics or Education, Licensed Professional Teacher, Strong communication skills",
    salary: "₱25,000 - ₱35,000/month",
    location: "Quezon City, Metro Manila",
    jobType: "full-time",
    status: "open",
    applicants: 2,
    postedAt: "2026-02-10",
  },
  "job-2": {
    id: "job-2",
    adminId: "admin-1",
    title: "Physics Teacher - Online Classes",
    subject: "Physics",
    description: "Seeking a qualified physics teacher to conduct online classes for high school students. Must be comfortable with virtual teaching platforms and interactive learning methods.",
    requirements: "Bachelor's degree in Physics or related field, Licensed Professional Teacher, Experience with online teaching",
    salary: "₱20,000 - ₱30,000/month",
    location: "Remote (Work from Home)",
    jobType: "part-time",
    status: "open",
    applicants: 1,
    postedAt: "2026-02-08",
  },
  "job-3": {
    id: "job-3",
    adminId: "admin-1",
    title: "English Literature & Writing Instructor",
    subject: "English",
    description: "Join our team as an English Literature and Writing instructor. Help students develop critical thinking and communication skills through engaging lessons.",
    requirements: "Bachelor's degree in English or Education, Strong writing and communication skills, 2+ years teaching experience",
    salary: "₱22,000 - ₱32,000/month",
    location: "Makati City, Metro Manila",
    jobType: "full-time",
    status: "open",
    applicants: 3,
    postedAt: "2026-02-01",
  },
  "job-4": {
    id: "job-4",
    adminId: "admin-1",
    title: "Science Teacher (Chemistry & Biology)",
    subject: "Science",
    description: "We need an enthusiastic science teacher specializing in Chemistry and Biology. Laboratory experience is a plus.",
    requirements: "Bachelor's degree in Chemistry, Biology, or related field, Licensed Professional Teacher, Laboratory safety certification preferred",
    salary: "₱24,000 - ₱34,000/month",
    location: "Pasig City, Metro Manila",
    jobType: "contract",
    status: "open",
    applicants: 2,
    postedAt: "2026-02-05",
  },
}

// Teacher applications to job postings
export const mockApplications: Record<string, any> = {
  "app-1": {
    id: "app-1",
    jobId: "job-1",
    teacherId: "teacher-1",
    teacherName: "John Smith",
    jobTitle: "High School Mathematics Teacher",
    coverLetter:
      "I am very interested in this mathematics teaching position. With my 8 years of experience and Master's degree in Mathematics, I am confident I can contribute significantly to your institution.",
    status: "pending",
    appliedAt: "2026-02-11",
  },
  "app-2": {
    id: "app-2",
    jobId: "job-2",
    teacherId: "teacher-1",
    teacherName: "John Smith",
    jobTitle: "Physics Teacher - Online Classes",
    coverLetter: "I have extensive experience in teaching physics and am well-versed in online teaching platforms. I would love to be part of your remote teaching team.",
    status: "accepted",
    appliedAt: "2026-02-12",
  },
  "app-3": {
    id: "app-3",
    jobId: "job-3",
    teacherId: "teacher-2",
    teacherName: "Sarah Johnson",
    jobTitle: "English Literature & Writing Instructor",
    coverLetter: "As an English literature specialist with 5 years of experience, I am passionate about helping students develop their writing and analytical skills.",
    status: "pending",
    appliedAt: "2026-02-13",
  },
  "app-4": {
    id: "app-4",
    jobId: "job-1",
    teacherId: "teacher-3",
    teacherName: "Miguel Santos",
    jobTitle: "High School Mathematics Teacher",
    coverLetter: "While my specialty is in Chemistry and Biology, I also have a strong foundation in mathematics and would be excited to contribute to your mathematics program.",
    status: "pending",
    appliedAt: "2026-02-14",
  },
  "app-5": {
    id: "app-5",
    jobId: "job-4",
    teacherId: "teacher-3",
    teacherName: "Miguel Santos",
    jobTitle: "Science Teacher (Chemistry & Biology)",
    coverLetter: "This position aligns perfectly with my expertise in Chemistry and Biology. I have 6 years of laboratory teaching experience and hold a Laboratory Safety certification.",
    status: "pending",
    appliedAt: "2026-02-15",
  },
}

export const mockLogs: any[] = [
  {
    id: "log-1",
    userId: "admin-1",
    userName: "Admin User",
    action: "job_posted",
    description: "Posted new job: High School Mathematics Teacher",
    timestamp: new Date("2026-02-10T10:30:00"),
  },
  {
    id: "log-2",
    userId: "teacher-1",
    userName: "John Smith",
    action: "application_submitted",
    description: "Applied for job: High School Mathematics Teacher",
    timestamp: new Date("2026-02-11T14:45:00"),
  },
  {
    id: "log-3",
    userId: "admin-1",
    userName: "Admin User",
    action: "teacher_approved",
    description: "Approved teacher: John Smith",
    timestamp: new Date("2026-01-16T09:15:00"),
  },
  {
    id: "log-4",
    userId: "teacher-2",
    userName: "Sarah Johnson",
    action: "registration_pending",
    description: "New teacher registration pending verification",
    timestamp: new Date("2026-02-01T11:20:00"),
  },
  {
    id: "log-5",
    userId: "admin-1",
    userName: "Admin User",
    action: "job_posted",
    description: "Posted new job: Physics Teacher - Online Classes",
    timestamp: new Date("2026-02-08T16:30:00"),
  },
]

// Forum data - Announcements and Threads
export const mockAnnouncements = [
  {
    id: "announcement-1",
    title: "Welcome to TeachConnect Forum",
    content: "We're excited to launch our new community forum! This is a space for teachers to connect, share experiences, and stay updated with important announcements. Please be respectful and professional in all interactions.",
    authorId: "admin-1",
    authorName: "Admin User",
    authorRole: "admin",
    createdAt: "2026-01-05T10:00:00",
    isPinned: true,
    views: 245,
    reactions: 38,
  },
  {
    id: "announcement-2",
    title: "New Job Posting Guidelines",
    content: "We've updated our job posting guidelines to ensure better quality and clarity. All job postings must now include detailed subject requirements, expected qualifications, and clear compensation information. Please review the updated guidelines in the Help section.",
    authorId: "admin-1",
    authorName: "Admin User",
    authorRole: "admin",
    createdAt: "2026-01-20T14:30:00",
    isPinned: true,
    views: 189,
    reactions: 24,
  },
  {
    id: "announcement-3",
    title: "Platform Maintenance Scheduled",
    content: "We will be performing scheduled maintenance on February 15, 2026, from 2:00 AM to 4:00 AM (GMT+8). The platform will be temporarily unavailable during this time. We apologize for any inconvenience.",
    authorId: "admin-1",
    authorName: "Admin User",
    authorRole: "admin",
    createdAt: "2026-02-05T09:00:00",
    isPinned: false,
    views: 156,
    reactions: 12,
  },
]

export const mockForumThreads = [
  {
    id: "thread-1",
    title: "Best Practices for Online Teaching",
    content: "I've been teaching online for 3 years now and wanted to share some tips that have really helped me connect with students. What are your experiences with online vs in-person teaching?",
    authorId: "teacher-1",
    authorName: "John Smith",
    category: "Discussion",
    createdAt: "2026-02-01T10:30:00",
    views: 87,
    replies: 12,
    lastActivity: "2026-02-10T15:20:00",
    tags: ["online-teaching", "best-practices", "tips"],
  },
  {
    id: "thread-2",
    title: "How to handle difficult classroom situations?",
    content: "As a new teacher, I sometimes struggle with classroom management. Any advice on handling disruptive students while maintaining a positive learning environment?",
    authorId: "teacher-3",
    authorName: "Maria Garcia",
    category: "Question",
    createdAt: "2026-02-03T14:15:00",
    views: 64,
    replies: 8,
    lastActivity: "2026-02-09T11:45:00",
    tags: ["classroom-management", "advice", "new-teacher"],
  },
  {
    id: "thread-3",
    title: "Sharing my lesson plans for Mathematics",
    content: "I've created a comprehensive set of lesson plans for Grade 10 Mathematics. Would anyone be interested in collaborating or sharing their own materials? I believe sharing resources can help us all improve.",
    authorId: "teacher-1",
    authorName: "John Smith",
    category: "Resources",
    createdAt: "2026-02-05T09:20:00",
    views: 103,
    replies: 15,
    lastActivity: "2026-02-11T16:30:00",
    tags: ["mathematics", "lesson-plans", "resources"],
  },
  {
    id: "thread-4",
    title: "Question about application process",
    content: "I recently submitted my application for a teaching position. How long does it typically take to hear back? Also, is there a way to track application status?",
    authorId: "teacher-2",
    authorName: "Sarah Johnson",
    category: "Question",
    createdAt: "2026-02-07T11:00:00",
    views: 45,
    replies: 5,
    lastActivity: "2026-02-08T10:15:00",
    tags: ["application", "process", "help"],
  },
  {
    id: "thread-5",
    title: "Success Story: My first month teaching",
    content: "Just wanted to share my experience! I got my first teaching job through TeachConnect last month and it's been an amazing journey. The students are engaged and the school environment is very supportive. Thank you to everyone who helped me prepare!",
    authorId: "teacher-4",
    authorName: "Robert Chen",
    category: "Discussion",
    createdAt: "2026-02-09T16:45:00",
    views: 92,
    replies: 18,
    lastActivity: "2026-02-11T14:20:00",
    tags: ["success-story", "first-job", "experience"],
  },
]

export const mockThreadReplies: Record<string, any[]> = {
  "thread-1": [
    {
      id: "reply-1-1",
      threadId: "thread-1",
      content: "Great topic! I find that using interactive tools like polls and breakout rooms really helps with engagement in online classes.",
      authorId: "teacher-2",
      authorName: "Sarah Johnson",
      createdAt: "2026-02-02T09:15:00",
      likes: 5,
    },
    {
      id: "reply-1-2",
      threadId: "thread-1",
      content: "I completely agree with the breakout rooms suggestion. I also make sure to have my camera on and encourage students to do the same - it creates a more personal connection.",
      authorId: "teacher-3",
      authorName: "Maria Garcia",
      createdAt: "2026-02-03T11:30:00",
      likes: 8,
    },
    {
      id: "reply-1-3",
      threadId: "thread-1",
      content: "One thing that's worked well for me is starting each session with a quick check-in. It helps build community and lets students share how they're doing.",
      authorId: "teacher-4",
      authorName: "Robert Chen",
      createdAt: "2026-02-04T14:20:00",
      likes: 12,
    },
    {
      id: "reply-1-4",
      threadId: "thread-1",
      content: "These are all excellent tips! I'd also add that recording sessions can be really helpful for students who need to review the material later.",
      authorId: "teacher-1",
      authorName: "John Smith",
      createdAt: "2026-02-05T10:45:00",
      likes: 6,
    },
  ],
  "thread-2": [
    {
      id: "reply-2-1",
      threadId: "thread-2",
      content: "Have you tried establishing clear classroom rules from day one? I post them visibly and review them regularly with students.",
      authorId: "teacher-1",
      authorName: "John Smith",
      createdAt: "2026-02-04T10:00:00",
      likes: 7,
    },
    {
      id: "reply-2-2",
      threadId: "thread-2",
      content: "Building positive relationships with students is key. Try to connect with the disruptive students one-on-one to understand what's going on.",
      authorId: "teacher-4",
      authorName: "Robert Chen",
      createdAt: "2026-02-05T15:30:00",
      likes: 9,
    },
    {
      id: "reply-2-3",
      threadId: "thread-2",
      content: "Consistency is everything! Make sure you follow through with consequences every time. Students need to know you mean what you say.",
      authorId: "teacher-2",
      authorName: "Sarah Johnson",
      createdAt: "2026-02-06T09:20:00",
      likes: 11,
    },
  ],
  "thread-3": [
    {
      id: "reply-3-1",
      threadId: "thread-3",
      content: "I'd love to see your lesson plans! I teach Grade 9 Math and I'm always looking for new ideas to improve my materials.",
      authorId: "teacher-2",
      authorName: "Sarah Johnson",
      createdAt: "2026-02-06T11:00:00",
      likes: 4,
    },
    {
      id: "reply-3-2",
      threadId: "thread-3",
      content: "This is awesome! Collaborative resource sharing is what makes our teaching community so strong. Count me in!",
      authorId: "teacher-3",
      authorName: "Maria Garcia",
      createdAt: "2026-02-07T14:15:00",
      likes: 6,
    },
    {
      id: "reply-3-3",
      threadId: "thread-3",
      content: "I have some interactive worksheets for algebra that I can share. Would you be interested in those?",
      authorId: "teacher-4",
      authorName: "Robert Chen",
      createdAt: "2026-02-08T10:30:00",
      likes: 8,
    },
  ],
  "thread-4": [
    {
      id: "reply-4-1",
      threadId: "thread-4",
      content: "In my experience, it usually takes about 3-5 business days for the admin team to review applications. Be patient!",
      authorId: "teacher-1",
      authorName: "John Smith",
      createdAt: "2026-02-07T13:00:00",
      likes: 3,
    },
    {
      id: "reply-4-2",
      threadId: "thread-4",
      content: "You can track your application status in the 'My Applications' section of your dashboard. Good luck!",
      authorId: "teacher-3",
      authorName: "Maria Garcia",
      createdAt: "2026-02-08T09:45:00",
      likes: 5,
    },
  ],
  "thread-5": [
    {
      id: "reply-5-1",
      threadId: "thread-5",
      content: "Congratulations! That's wonderful to hear. Your success story is inspiring for all of us!",
      authorId: "teacher-1",
      authorName: "John Smith",
      createdAt: "2026-02-10T09:00:00",
      likes: 15,
    },
    {
      id: "reply-5-2",
      threadId: "thread-5",
      content: "So happy for you! This gives me hope as I'm still waiting to hear back from my applications.",
      authorId: "teacher-2",
      authorName: "Sarah Johnson",
      createdAt: "2026-02-10T11:30:00",
      likes: 8,
    },
    {
      id: "reply-5-3",
      threadId: "thread-5",
      content: "Amazing! Which school did you end up joining? I'm curious about different school environments.",
      authorId: "teacher-3",
      authorName: "Maria Garcia",
      createdAt: "2026-02-10T14:00:00",
      likes: 6,
    },
    {
      id: "reply-5-4",
      threadId: "thread-5",
      content: "Welcome to the teaching family! Keep up the great work and don't hesitate to ask for help when you need it.",
      authorId: "teacher-4",
      authorName: "Robert Chen",
      createdAt: "2026-02-11T10:15:00",
      likes: 10,
    },
  ],
}

